[build]
command = "bundle install && bundle exec jekyll build"
publish = "_site"

[build.environment]
RUBY_VERSION = "3.4.2"
BUNDLE_PATH = "vendor/bundle"

[[plugins]]
  package = "@netlify/plugin-cache"
