title: doc-site
description: Site de documentation de votre projet
theme: just-the-docs

url: https://github.com/dsissoko

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.4.1"

aux_links_new_tab: true

aux_links:
  C4 Model:
   - https://c4model.com/
  Mermaid:
   - https://mermaid.js.org/ecosystem/tutorials.html
  Just-The-Docs:
   - https://just-the-docs.com/
  Jekyll:
   - https://jekyllrb.com/
  Github pages:
   - https://pages.github.com/
  Netlify:
   - https://www.netlify.com/
  #matyalatte Playground:
   #- https://github.com/matyalatte/doc_test

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

sass:
  quiet_deps: true

logo: "/assets/images/logo_ds.png"
favicon_ico: "/assets/images/favicon.ico"
