title: Documentation R3edge
description: Documentation du moteur et de l'appli r3edge
theme: just-the-docs

url: https://r3edge.com

aux_links_new_tab: true

aux_links:
  Kucoin:
   - https://www.kucoin.com
  Kraken:
   - https://www.kraken.com

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

