title: doc-site
description: site de documentation de votre projet
theme: just-the-docs

url: https://just-the-docs.com/

aux_links_new_tab: true

aux_links:
  Just-The-Docs:
   - https://just-the-docs.com/
  Jekyll:
   - https://jekyllrb.com/
  Github pages:
   - https://pages.github.com/
  Netlify:
   - https://www.netlify.com/  

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

